TEXTURE_ATLAS_PATH = './Assets/Tiles.png'

TEXTURE_TILE_SIZE_PX = 16
TEXTURE_N_TILES_PER_ROW = 4
TEXTURE_TILE_SIZE_NORMALIZED = 1 / TEXTURE_N_TILES_PER_ROW
TEXTURE_TILE_PADDING = 1 / 4096

TILEMAP_N_ROWS = 36
TILEMAP_N_COLS = 28

WINDOW_MINIMUM_SIZE = (TILEMAP_N_COLS * TEXTURE_TILE_SIZE_PX, TILEMAP_N_ROWS * TEXTURE_TILE_SIZE_PX)

SHADERS_FOLDER = './Shaders'